<div class=content>
<h1 id=about>About</h1>
<h2 id="about-the-unified-model-binary-umb-standard">About the Unified
Model Binary (UMB) Standard</h2>
<p>The <em>Unified Model Binary (UMB)</em> standard represents a
significant advancement in modeling techniques, establishing a common
language for diverse models while excluding symbolic representations for
clarity and focus. Designed to express the least common multiple of
various models, UMB ensures comprehensive support for a wide range of
scenarios, with a commitment to mathematical precision and usability. By
utilizing standard primitive data structures in a JSON format, UMB
achieves a unique balance of expressiveness, speed, and
conciseness—positioning it as an efficient tool for model
representation.</p>
<hr />
<h2 id="ecosystem-surrounding-umb">Ecosystem Surrounding UMB</h2>
<p>UMB is supported by a robust ecosystem that includes <em>UMBI</em>,
its reference implementation, which enhances user experience by
providing tools for model conversion and input. The collaborative
framework surrounding UMB features support from multiple observatories
that facilitate integration with various modeling tools and
environments. This infrastructure allows users to leverage UMB’s
capabilities seamlessly, exploring previously unattainable modeling
possibilities and enhancing overall usability.</p>

<h2 id="use-cases-and-consequences">Use Cases and Consequences</h2>
<p>The UMB format and its ecosystem unlock numerous capabilities for
both users and researchers in the field of <a
href="https://prismmodelchecker.org/lectures/pmc/">Probabilistic Model
Checking (PMC)</a>. Below are some notable scenarios where UMB provides
significant advantages:</p>
<h3 id="benefits-for-users-of-pmc">Benefits for Users of PMC</h3>
<ul>
<li><p><strong>Access to the Entire Ecosystem</strong>: UMB support
opens doors to tools like <a
href="https://github.com/pysmt/pysmt">pySMT</a> and <a
href="https://pypi.org/project/PuLP/">PuLP</a>, allowing users to chain
various tools effortlessly. For instance, a complex model generated by
<a href=#>Modest</a> or <a href="https://staminachecker.org">STAMINA</a> can be
processed using <a href="https://stormchecker.org">Storm</a> and then
enhanced with player additions via UMBI, with final verification
conducted in <a href="https://prismmodelchecker.org">PRISM</a>.</p></li>
<li><p><strong>Visualization Capabilities</strong>: Users can visualize
models easily. Many model-visualization tools such as <a
href="https://github.com/stormchecker/stormvogel">StormVogel</a> support
UMB.</p></li>
<li><p><strong>Portfolio Approaches</strong>: UMB’s design allows for
the easy composition and modification of models, making it
straightforward to implement various modeling approaches—like generating
biology models from simple equations—where traditional formats like <a
href="https://jani-spec.org/">JANI</a> or <a
href="https://www.prismmodelchecker.org/manual/ThePRISMLanguage/Introduction">PRISM</a>
would struggle.</p></li>
<li><p><strong>Ease of Modification</strong>: Users can dynamically
change models—such as adjusting transition probabilities or
representation styles—facilitating agile development and
testing.</p></li>
<li><p><strong>Parallelization Potential</strong>: Large models can be
efficiently distributed across different servers.</p></li>
</ul>
<h3 id="benefits-for-researchers-and-tool-developers">Benefits for
Researchers and Tool Developers</h3>
<ul>
<li><p><strong>Independent Algorithm Testing</strong>: Researchers can
conduct fair comparisons of algorithms without the distortions caused by
state space exploration differences, achieving consistent
benchmarks.</p></li>
<li><p><strong>Prototyping Flexibility</strong>: UMB allows for easy
prototyping of new model types, broadening the frontiers of
expressiveness in PMC. If existing tools do not support a desired model,
UMBI facilitates straightforward solutions for new
implementations.</p></li>
<li><p><strong>Random Model Generation</strong>: The ease of generating
random models speeds up experimentation and testing, addressing
inefficiencies in previous systems.</p></li>
</ul>
</div>
